name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm install
      - run: npx astro compile
      - name: Deploy to GitHub Pages
        run: |
          echo 'sub.mydomain.com' > public/CNAME # Si usas un dominio personalizado
          git add .
          git commit -m "Build and deploy"
          git push
